# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo 
      uses: actions/checkout@v2
      
    - name: set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Change wrapper permissions
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Generate Documentation
      uses: ./gradlew dokkaGfm
      
    - name: Commit
      run: |
        git config --local user.name "Shimunz"  
        git config --local user.email "simonzhao@outlook.com"
        git add.
        git commit -m "Updated documentation"
    
    - name: Deploy API documentation to Github Pages
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FOLDER: build/dokka/GFM
